FROM rust:1.70 as builder
WORKDIR /usr/src/backend
COPY . .
RUN cargo install --path .
FROM debian:buster-slim
RUN apt-get update & apt-get install -y extra-runtime-dependencies & rm -rf /var/lib/apt/lists/*
COPY --from=builder /usr/local/cargo/bin/backend /usr/local/bin/backend
EXPOSE 8000
CMD ["backend"]